[project]
name = "torch-flow-models"
version = "2025.02.18"
requires-python = ">= 3.11.11"
dependencies = [
    "torch==2.6.0",
    "numpy==2.2.3",
    "scikit-learn==1.6.1",
    "gitpython",
]
readme = "README.md"
